x-app: &app
  env_file:
    - ./.env
  restart: no
  platform: linux/amd64

services:

  postgres:
    container_name: lisema-postgres
    image: postgres:15-alpine
    <<: *app
    ports:
      - "54325:5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - "data-postgres:/var/lib/postgresql/data"

  pgadmin:
    container_name: lisema-pgadmin
    image: dpage/pgadmin4:latest
    <<: *app
    ports:
      - "8085:80"
    volumes:
      - "data-pgadmin:/var/lib/pgadmin"
    depends_on:
      postgres:
        condition: service_healthy

  redis:
    container_name: lisema-redis
    platform: linux/amd64
    image: redis:7.4-rc1-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth:
    container_name: lisema-auth
    build:
      context: ./services/auth
    <<: *app
    volumes:
      - ./services/auth:/usr/src/app/
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - 8005:8000
    expose:
      - "8000"

volumes:
  data-pgadmin:
  data-postgres: